### ISSUE TITLE
Delete user button

### ISSUE THREAD

**Issue by SkySourced** [ducksteam/findtheducks#32]
we should have one just in case

**Comment by Thechiefpotatopeeler** [comment]
Is this for deleting one's own user or for admins to delete a user?

**Comment by SkySourced** [comment]
One's own user

**Comment by Thechiefpotatopeeler** [comment]
Is it gonna be like remove them from the table or just lock them out?

**Comment by SkySourced** [comment]
Remove from the table and remove their finds and update any firsts
